imu0: "/imu/filtered/data"   
#The order of the values is x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az.
 
imu0_config: [false, false, false,
              false,  false,  true,
              false, false, false,
              false,  false,  true,
              false,  false,  false]

#imu0_config: [false, false, false,
#              false,  false,  false,
#              false, false, false,
#              false,  false,  false,
#              false,  false,  false]




imu0_differential: true
imu0_relative: false
imu0_remove_gravitational_acceleration: false

# ======== ADVANCED PARAMETERS ======== 
imu0_queue_size: 50