odom2: "/odom_wheels"

#The order of the values is x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az.
odom2_config: [true, true, true,
               true, true, true,
               true, true, true,
               true, true, true,
               true, true, true]

odom2_differential: false
odom2_relative: true

# ======== ADVANCED PARAMETERS ========
odom2_queue_size: 5


