odom0: "/odom_wheels"

#The order of the values is x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az.
odom0_config: [true, true, true,
               true, true, true,
               true, true, true,
               true, true, true,
               true, true, true]

odom0_differential: false
odom0_relative: true

# ======== ADVANCED PARAMETERS ========
odom0_queue_size: 5


